### ISSUE TITLE
make Charts available for Kubernetes 1.24+

### ISSUE THREAD

**Issue by mabahre** [rancher/vsphere-charts#48]
Hello,

at the Moment the Charts are not available in a Cluster with Kubernetes 1.24.
Would it be possible to make them compatible with this?

I know that the original Vsphere Charts already compatible with Kubernetes 1.24, but for Upgrade Reasons I'm waiting for them to become available trough Rancher.

Kind Regards

**Comment by snasovich** [comment]
@mabahre , could you please clarify version of Rancher and your cluster configuration?

The currently released charts for Rancher 2.6.x versions have support for k8s 1.24 -
https://github.com/rancher/charts/blob/release-v2.6/charts/rancher-vsphere-cpi/100.5.0%2Bup1.4.1/values.yaml#L35-L39
https://github.com/rancher/charts/blob/release-v2.6/charts/rancher-vsphere-csi/100.4.0%2Bup2.6.2-rancher1/values.yaml#L154-L174

**Comment by mabahre** [comment]
I'm using Rancher v2.7.1 at the Moment with a vsphere provisioned Cluster (1.24.19-rancher-4-1).
May I have to add one Information. The CPI is available, I see it under Apps>Charts, but the CSI is missing. In our Productive Clusters with are still on 1.23 both are visible and in Uuse.

**Comment by mabahre** [comment]
The Charts are now available for me.
The Ticket can be closed.
