### ISSUE TITLE
Missing the CSI Snapshotter sidecar - blockSnapshots will never work

### ISSUE THREAD

**Issue by braunsonm** [rancher/vsphere-charts#50]
**vSphere Server Info**
- vSphere version: 7.0.3

**Rancher Server Setup**
- Rancher version: 2.7.3

**Information about the Cluster**
- Kubernetes version: 1.25.7 RKE2

**Describe the bug**
RKE2 has added the snapshot controllers and vSphere CSI supports VolumeSnapshots. In fact, this chart added a feature flag to add support [here](https://github.com/rancher/vsphere-charts/blob/main/charts/rancher-vsphere-csi/values.yaml#L75) however it seems like it was forgotten that the CSI Snapshotter sidecar is required, as per VMware's installation instructions: https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.4.0/manifests/vanilla/deploy-csi-snapshot-components.sh

Notice they apply the following patch:
```sh
# Update the vSphere CSI driver to add the snapshot side car.
tmpdir=$(mktemp -d)
echo "creating patch file in tmpdir ${tmpdir}"
cat <<EOF >> "${tmpdir}"/patch.yaml
spec:
  template:
    spec:
      containers:
        - name: csi-snapshotter
          image: 'k8s.gcr.io/sig-storage/csi-snapshotter:${release}'
          args:
            - '--v=4'
            - '--timeout=300s'
            - '--csi-address=\$(ADDRESS)'
            - '--leader-election'
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
EOF

echo -e "Patching vSphere CSI driver.."
kubectl patch deployment vsphere-csi-controller -n vmware-system-csi --patch "$(cat "${tmpdir}"/patch.yaml)"
echo -e "✅ Successfully patched vSphere CSI driver, please wait till deployment is updated.."
echo -e "\n✅ Successfully deployed all components for CSI Snapshot feature.\n"
```

**To Reproduce**
Create a VolumeSnapshotDriver and a VolumeSnapshot with `blockSnapshots` enabled. You will notice that the snapshot will never complete.

**Expected Result**
The snapshot should complete and the CSI Snapshotter should be added as a sidecar

**Comment by santimar** [comment]
This chart should also install the other resources listed within the `deploy-csi-snapshot-components.sh`script

1. Deploys the VolumeSnapshot CRDs
2. Creates RBAC rules to support VolumeSnapshot
3. Deploys snapshot-controller in kube-system namespace
4. Deploys the snapshot validation webhook
5. Patches vSphere CSI driver to deploy the csi-snapshotter sidecar

Otherwise the cluster will still lack support for Snapshot, doesn't it?

**Comment by braunsonm** [comment]
RKE2 already does those steps I believe. @santimar

**Comment by santimar** [comment]
I do not see any `VolumeSnapshotClass` after the CSI is installed.
Do i need to create it by myself? `StorageClass` is created automatically

**Comment by nicolascousin** [comment]
I deployed rancher-vsphere-csi:100.4.0+up2.6.2-rancher1 on my RKE1 cluster. Can I get Snapshot support ? Do I need to wait for an update of this chart ?

**Comment by mymasse** [comment]
Any progress on this issue?

**Comment by braunsonm** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/41321 which is now assigned
