### ISSUE TITLE
CSI-Snapshotter sidecar container not available as part of vSphere CSI Controller

### ISSUE THREAD

**Issue by srivallabandev** [rancher/vsphere-charts#67]
Rancher version : 
2.6.x and 2.7.x

RKE2 Version: 
v1.27.10+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux xxxx 5.3.18-150300.59.144-default rancher/rke2#1 SMP Tue Dec 5 15:20:50 UTC 2023 (5dc33fd) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master 2 workers

**Describe the bug:**
The vsphere-csi-controller pod running in the kube-system namespace doesn't have the csi-snapshotter side car container that orchestrates the creation of the volume snapshot. The VolumeSnapshot related CRDs are present. This side car container is one of the prerequsites mentioned in the Volume Snapshot official documentation.

**Steps To Reproduce:**
 Install RKE2 and check the vsphere-csi-controller pods, there wont be csi-snapshotter sidecar container

**Expected behavior:**
CSI snapshotter sidecar container to be part of vSphere CSI controller pods. since we are using the helm based deployment from Rancher , this should be part of the helm chart.

**Actual behavior:**
csi-snapshotter sidecar not part of the vSphere csi controller

**Additional context / logs:**
VolumeShapshot related CRDs are available from release 1.26.x but for it to work , CSI snapshotter side car container is necessary as per the CSI volume shapshot documentation. Rancher chart for the vSphere CSI doesn't have this sidecar container. we have added it manually to test the functionality

Screenshots
we added this sidecar manually to the vSphere CSI controller pod, image for reference
![image](https://github.com/rancher/rke2/assets/149671885/79b3cdbb-e9b3-45e2-b2e7-b7d6a6ceab51)

**Comment by r0k5t4r** [comment]
Hi,

any progress / news on this issue? I struggled for hours to get volume snapshots working with Velero until I figured this out. :(

I would also be happy with some simple steps how to add the side car.

Cheers,
Oliver

**Comment by brandond** [comment]
Do you have a reference to the upstream vsphere CSI docs on how the "sidecar" is supposed to be deployed? Calling it a sidecar suggests that there's supposed to be a controller that injects it into the pod, but it sounds like it's just another controller that needs to run somewhere in the cluster?

**Comment by brandond** [comment]
A quick glance at the chart templates suggests that this already exists, and simply requires setting `blockVolumeSnapshot.enabled=true` in the chart values. Have you tried doing so?

Ref: https://github.com/rancher/vsphere-charts/blob/48ef73475a0c774374bad144d82778cc11596cde/charts/rancher-vsphere-csi/templates/controller/deployment.yaml#L129-L153

**Comment by r0k5t4r** [comment]
Hi,

and wow. Thanks for the quick reply. I also just found another github issue: 

[](https://github.com/rancher/rancher/issues/41321)

where they pointed out one has to use:

blockVolumeSnapshot:
  enabled: true

to enable the sidecar.

How can I do this now that I have already deployed the cluster?

Worst case I can re-deploy the cluster, but would be cool to just add this afterwards.

Cheers,
Oliver

**Comment by brandond** [comment]
Yes, that's the same chart value.

It looks like there's not a UI option for this via questions.yaml, but you should be able to edit the cluster config YAML to set it. It'll be in the rkeConfig.chartValues section:

```yaml
  rkeConfig:
    chartValues:
      rancher-vsphere-csi:
        blockVolumeSnapshot:
          enabled: true
```

**Comment by brandond** [comment]
I opened a PR to add a question to questions.yaml, which will add a checkbox for this in the Rancher UI.
