### ISSUE TITLE
cpi deployement issue

### ISSUE THREAD

**Issue by tsikkema** [rancher/vsphere-charts#83]
**vSphere Server Info**
- vSphere version: 8.0.2.00300

**Rancher Server Setup**
- Rancher version: 2.8.5
- Installation option (Docker install/Helm Chart): app chart install

**Information about the Cluster**
- Kubernetes version: 1.28.10+rke2r1

**Describe the bug**
failed to create listener: failed to listen on 0.0.0.0:10260: listen tcp 0.0.0.0:10260: bind: address already in use

**To Reproduce**
 

**Result**
adding "--webhook-secure-port=10264 --secure-port=10274" to daemonset arguments config

**Expected Result**
allow it to be configured from chart screen or resolve bug that webhook port doesn't use secure port.

**Comment by brandond** [comment]
It is not supported to install the vsphere CPI or CSI in to RKE2 via the app catalog.

If provisioning RKE2 via Rancher, you should select the vsphere cloud provider when provisioning the cluster.

If provisioning a standalone RKE2 cluster, you should set --cloud-provider=rancher-vsphere on the command line or in the config file.
