### ISSUE TITLE
add upstream support of JSON logging

### ISSUE THREAD

**Issue by dmpe** [rancher/vsphere-charts#95]
**Is your feature request related to a problem? Please describe.**

Following containers have JSON support build in. It just needs to be enabled in the helm chart via some if/else construct. 
So my question is: could it be done ?

- `csi-node-driver-registrar` -> https://github.com/kubernetes-csi/node-driver-registrar/blob/release-2.12/CHANGELOG/CHANGELOG-2.11.md
- `livenessprobe` -> https://github.com/kubernetes-csi/livenessprobe/blob/release-2.14/CHANGELOG/CHANGELOG-2.13.md

and I also guess all images under https://github.com/rancher/vsphere-charts/blob/main/charts/rancher-vsphere-csi/values.yaml#L247

Example: csi attacher has added JSON logging in https://github.com/kubernetes-csi/external-attacher/blob/master/CHANGELOG/CHANGELOG-4.6.md version. 

**Describe the solution you'd like**

I would like that all CSI containers log in JSON format, instead of default `text` format. It should also configurable in the helm chart. 

Rancher GUI `2.9.2` + downstream cluster `v1.30.4+rke2r1`

**Comment by snasovich** [comment]
@dmpe , thank you for submitting this enhancement request.
I guess it should be possible by adding support to provide additional args to these containers via `values.yaml` (at a glance they should probably go here - https://github.com/rancher/vsphere-charts/blob/a5c99d716df960dc50cf417d9ecffad6b55ca0ad/charts/rancher-vsphere-csi/values.yaml#L189-L200 for `registrar` and Helm template around https://github.com/rancher/vsphere-charts/blob/a5c99d716df960dc50cf417d9ecffad6b55ca0ad/charts/rancher-vsphere-csi/templates/node/daemonset.yaml#L72-L75 should be updated to use these additional args) - that's one of possible solutions. However, at this time this enhancement is not prioritized - but we welcome community contributions. ;)
